name: to_dont_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/paw_wallpaper.jpg


  # fonts:
    # - asset: fonts/cool_font/atop/atop2.ttf
    # style: const TextStyle(color: Color.fromARGB(255, 63, 129, 160))

        
